[package]
name = "iarmap"
version = "0.1.0"
authors = ["Ian McIntyre <me@ianpmcintyre.com>"]

[dependencies]
nom = "3.2.0"
colored = "1.6"

[lib]
name = "iarmap"
path = "src/lib.rs"

[[bin]]
name = "iarmapcmp"
path = "bin/main.rs"